// BATCH C – Earth Science f2-f3, Health f2, Arts f1-f2, Music f1-f2, PE f1-f2,
//           Religion-Ethics f2, Social Studies f2, Philosophy f2, Technology f2
//           + ALL 7 new school subjects (politics-civics, psychology-school,
//             astronomy, latin-language, media-studies, chinese-language, environmental-studies)
const fs = require('fs');
const path = require('path');
const enPath = path.join(__dirname, '../locales/en.json');
const en = JSON.parse(fs.readFileSync(enPath, 'utf8'));

const keys = {

  // ── Earth Science f2-f3 ────────────────────────────────────────────────

  "learnSch_earth_science_f2_name": "Oceans & the Water Cycle",
  "learnSch_earth_science_f2_desc": "Oceans cover 71% of Earth's surface and regulate climate, produce oxygen, and support extraordinary biodiversity. The water cycle continuously moves water between oceans, atmosphere, and land, making Earth the only planet with liquid water at its surface — a key condition for life.",
  "learnSch_earth_science_f2_kp0": "The water cycle: evaporation (liquid to gas, driven by solar energy) → condensation (gas to droplets, forming clouds) → precipitation (rain, snow) → run-off and infiltration → back to evaporation.",
  "learnSch_earth_science_f2_kp1": "Oceans store heat and moderate climate: they absorb CO₂ and heat from the sun, releasing it slowly and buffering temperature extremes.",
  "learnSch_earth_science_f2_kp2": "Ocean currents (e.g. Gulf Stream) transfer heat around the globe, warming or cooling coastal regions far from the equator.",
  "learnSch_earth_science_f2_kp3": "Ocean acidification: as CO₂ dissolves in seawater it forms carbonic acid (H₂CO₃), lowering pH and threatening coral reefs and shellfish.",
  "learnSch_earth_science_f2_kp4": "Groundwater: water stored in underground aquifers. Over-extraction depletes aquifers faster than they recharge — a growing global water security issue.",
  "learnSch_earth_science_f2_task": "Draw and fully label the water cycle. For each stage, state the physical process involved (evaporation, condensation, etc.) and the energy source driving it. Then explain two human activities that disrupt the water cycle.",
  "learnSch_earth_science_f2_tp0": "Water cycle stages",
  "learnSch_earth_science_f2_tp1": "Ocean currents and climate",
  "learnSch_earth_science_f2_tp2": "Ocean acidification",

  "learnSch_earth_science_f3_name": "Natural Hazards & Disasters",
  "learnSch_earth_science_f3_desc": "Natural hazards — earthquakes, volcanoes, tsunamis, hurricanes — arise from Earth's internal and atmospheric energy. Understanding their causes, distribution, and effects allows societies to prepare, mitigate damage, and save lives. The risk to human populations depends as much on social and economic factors as on the physical hazard itself.",
  "learnSch_earth_science_f3_kp0": "Earthquakes occur at tectonic plate boundaries (conservative, destructive, constructive). The Richter / moment magnitude scale measures energy release; each unit = ×32 times more energy.",
  "learnSch_earth_science_f3_kp1": "Volcanoes form at subduction zones (explosive, viscous lava) and at hotspots/constructive boundaries (effusive, runny lava, e.g. Iceland, Hawaii).",
  "learnSch_earth_science_f3_kp2": "Tsunamis are giant ocean waves triggered by undersea earthquakes or volcanic eruptions. The 2004 Indian Ocean tsunami killed ~230,000 people.",
  "learnSch_earth_science_f3_kp3": "Tropical cyclones (hurricanes/typhoons) form over warm ocean water (≥26°C). They bring extreme winds, storm surges, and flooding.",
  "learnSch_earth_science_f3_kp4": "Vulnerability to natural hazards depends on poverty, building quality, warning systems, and governance — poorer countries suffer disproportionately.",
  "learnSch_earth_science_f3_task": "Compare the causes and effects of a major earthquake (e.g. Haiti 2010) with a major volcanic eruption (e.g. Mount Pinatubo 1991). Use a table: Cause, Magnitude, Primary effects, Secondary effects, Human response.",
  "learnSch_earth_science_f3_tp0": "Earthquakes and volcanoes",
  "learnSch_earth_science_f3_tp1": "Tsunamis",
  "learnSch_earth_science_f3_tp2": "Risk, vulnerability, and management",

  // ── Health Education f2 ────────────────────────────────────────────────

  "learnSch_health_f2_name": "First Aid & Personal Safety",
  "learnSch_health_f2_desc": "First aid is the immediate assistance given to an injured or ill person before professional medical help arrives. Knowing first aid saves lives — including the 'chain of survival' in cardiac arrest. Personal safety knowledge helps prevent accidents, recognise danger, and make good decisions in emergencies.",
  "learnSch_health_f2_kp0": "The primary survey (ABCDE): Airway, Breathing, Circulation, Disability (level of consciousness), Exposure (visible injuries).",
  "learnSch_health_f2_kp1": "CPR (Cardiopulmonary Resuscitation): 30 chest compressions at 5–6 cm depth and ~100–120 per minute, then 2 rescue breaths. Repeat until help arrives.",
  "learnSch_health_f2_kp2": "Recovery position: for an unconscious but breathing person — prevents choking on vomit and keeps airway open.",
  "learnSch_health_f2_kp3": "For burns: cool under cool running water for 10 minutes. Do NOT use ice, butter, or toothpaste. Cover with a clean non-fluffy dressing.",
  "learnSch_health_f2_kp4": "Calling emergency services: state your location, the nature of the emergency, and the number of people affected. Stay on the line and follow instructions.",
  "learnSch_health_f2_task": "Write a step-by-step guide for responding to a person who has collapsed and is unresponsive. Include: checking for safety, assessing consciousness, calling for help, CPR steps, and when to stop. Include approximate numbers (compression rate, depth).",
  "learnSch_health_f2_tp0": "Primary survey (ABCDE)",
  "learnSch_health_f2_tp1": "CPR and recovery position",
  "learnSch_health_f2_tp2": "Burns, bleeding, and choking",

  // ── Arts f1-f2 ─────────────────────────────────────────────────────────

  "learnSch_arts_f1_name": "Techniques & Art Media",
  "learnSch_arts_f1_desc": "Artists choose from a vast range of techniques and materials — drawing, painting, printmaking, sculpture, digital art — each with distinct qualities and uses. Understanding different art media helps you select the right tool for your artistic intention, and builds a vocabulary to discuss and evaluate artworks critically.",
  "learnSch_arts_f1_kp0": "Drawing media: pencil (graphite), charcoal, ink — each produces different line quality, tone, and texture. Shading techniques: hatching, cross-hatching, stippling, blending.",
  "learnSch_arts_f1_kp1": "Painting media: watercolour (transparent, light areas left unpainted), acrylics (water-based, fast-drying, versatile), oils (slow-drying, rich colour, traditional glazing technique).",
  "learnSch_arts_f1_kp2": "Printmaking: relief printing (linocut — cutting away to leave the design), screen printing, etching — multiple identical prints from one matrix.",
  "learnSch_arts_f1_kp3": "Sculpture: additive (clay modelling, assemblage), subtractive (carving stone or wood), casting (bronze, resin). Installation art uses space itself as a medium.",
  "learnSch_arts_f1_kp4": "Digital art tools (Procreate, Photoshop, Blender) replicate and extend traditional techniques — layers, brushes, and 3D modelling — but require knowledge of the same underlying principles.",
  "learnSch_arts_f1_task": "Choose one artwork and one art medium you have not used before. Research its properties, then create a study using that medium. Write 150 words evaluating what worked, what was difficult, and how the medium affected the result.",
  "learnSch_arts_f1_tp0": "Drawing and mark-making",
  "learnSch_arts_f1_tp1": "Painting and printmaking",
  "learnSch_arts_f1_tp2": "Sculpture and digital art",

  "learnSch_arts_f2_name": "Colour Theory",
  "learnSch_arts_f2_desc": "Colour is the most powerful visual element — it evokes emotion, creates depth, and guides the viewer's eye. Colour theory explains the relationships between colours and how to use them intentionally. From the colour wheel to optical mixing, mastering colour transforms the impact of any artwork.",
  "learnSch_arts_f2_kp0": "Primary colours (RYB for paint: red, yellow, blue) cannot be made by mixing. Secondary colours (orange, green, purple) are made from two primaries.",
  "learnSch_arts_f2_kp1": "Complementary colours sit opposite each other on the colour wheel (e.g. red–green, blue–orange). Placed side by side they intensify each other; mixed they neutralise to grey/brown.",
  "learnSch_arts_f2_kp2": "Colour temperature: warm colours (reds, oranges, yellows) feel energetic and advance visually. Cool colours (blues, greens, purples) feel calm and recede.",
  "learnSch_arts_f2_kp3": "Tint = colour + white (lighter). Shade = colour + black (darker). Tone = colour + grey. These create value range in an artwork.",
  "learnSch_arts_f2_kp4": "Analogous colour schemes (adjacent colours) create harmony. Triadic schemes (three equally-spaced colours) create vibrant contrast. Monochromatic uses one hue in different values.",
  "learnSch_arts_f2_task": "Create a colour wheel showing all 12 hues (3 primary, 3 secondary, 6 tertiary). Then paint or draw two small squares side by side using a complementary pair and explain the visual effect. Annotate with: tint, shade, and tone of one colour.",
  "learnSch_arts_f2_tp0": "Colour wheel and mixing",
  "learnSch_arts_f2_tp1": "Complementary and analogous schemes",
  "learnSch_arts_f2_tp2": "Colour temperature and emotion",

  // ── Music f1-f2 ────────────────────────────────────────────────────────

  "learnSch_music_f1_name": "Instruments & Musical Genres",
  "learnSch_music_f1_desc": "The world's musical instruments are grouped into families by how they produce sound. Musical genres — from classical to jazz to hip-hop — reflect culture, history, and social context. Knowing instruments and genres gives you both a practical vocabulary and a wider appreciation of music as a living, evolving art form.",
  "learnSch_music_f1_kp0": "Instrument families: strings (violin, guitar — vibrating strings), woodwind (flute, clarinet — vibrating air column), brass (trumpet, trombone — buzzing lips), percussion (drums, xylophone — struck), keyboard (piano, organ — multiple mechanisms).",
  "learnSch_music_f1_kp1": "Orchestra sections: strings, woodwind, brass, percussion. The conductor coordinates all sections using gesture and a baton.",
  "learnSch_music_f1_kp2": "Classical music (1750–1820): structured forms (sonata, symphony, concerto), composers like Mozart, Haydn, Beethoven. Romantic music (1820–1900): more emotional expression, larger orchestras, Brahms, Tchaikovsky, Wagner.",
  "learnSch_music_f1_kp3": "Jazz (1900s, African-American origins): improvisation, syncopation, swing rhythm. Sub-genres: bebop, cool jazz, fusion. Blues: call-and-response, 12-bar form.",
  "learnSch_music_f1_kp4": "Pop and rock (1950s–): electric guitar, bass, drums, vocals. Hip-hop (1970s, Bronx NY): DJing, sampling, rapping, breakdancing — a complete cultural movement.",
  "learnSch_music_f1_task": "Listen to one piece from each of two different genres (e.g. a Beethoven symphony and a blues song). For each: identify instruments used, tempo, dynamics, mood, and one musical feature specific to that genre. Compare them in a table.",
  "learnSch_music_f1_tp0": "Instrument families",
  "learnSch_music_f1_tp1": "Classical and Romantic music",
  "learnSch_music_f1_tp2": "Jazz, blues, and contemporary genres",

  "learnSch_music_f2_name": "Music History",
  "learnSch_music_f2_desc": "Music history traces how musical styles, instruments, and ideas have evolved across centuries and cultures. From Gregorian chant to Beethoven's symphonies to electronic dance music, each era reflects its society's values, technology, and world view. Understanding music history deepens appreciation and puts current music in context.",
  "learnSch_music_f2_kp0": "Medieval (500–1400): Gregorian chant (monophonic, unaccompanied vocal music for the church). Renaissance (1400–1600): polyphony (multiple independent vocal parts); secular music emerges.",
  "learnSch_music_f2_kp1": "Baroque (1600–1750): J.S. Bach, Handel, Vivaldi. Ornate counterpoint, basso continuo, forms: fugue, suite, oratorio. Opera invented in Florence (~1600).",
  "learnSch_music_f2_kp2": "Classical period (1750–1820): balance, clarity, development of symphony, sonata form, string quartet. Mozart, Haydn, early Beethoven.",
  "learnSch_music_f2_kp3": "Romantic era (1820–1900): emotional intensity, programme music (tells a story), nationalism (Grieg, Sibelius, Dvořák), greatly expanded orchestras.",
  "learnSch_music_f2_kp4": "20th century: Modernism (Stravinsky, Schoenberg's 12-tone system), Jazz Age, Rock & Roll revolution (1950s), minimalism (Philip Glass), and the digital revolution creating electronic and computer music.",
  "learnSch_music_f2_task": "Create a timeline of Western music from 500 CE to the present. For each period: write the name, dates, two composers/artists, one key musical feature, and one characteristic instrument or form. Illustrate or annotate one musical excerpt from each period.",
  "learnSch_music_f2_tp0": "Medieval, Renaissance, Baroque",
  "learnSch_music_f2_tp1": "Classical and Romantic eras",
  "learnSch_music_f2_tp2": "20th century to present",

  // ── Physical Education f1-f2 ───────────────────────────────────────────

  "learnSch_physical_education_f1_name": "Team Sports & Tactics",
  "learnSch_physical_education_f1_desc": "Team sports develop physical skills, tactical thinking, communication, and leadership. Whether football, basketball, volleyball, or handball — each demands an understanding of rules, positions, and team strategies. Learning to read the game and make quick decisions is as important as physical ability.",
  "learnSch_physical_education_f1_kp0": "Communication: calling for the ball, organising defence, and encouraging teammates are as important as technical skill in team sports.",
  "learnSch_physical_education_f1_kp1": "Tactics in football: formations (4-4-2, 4-3-3) determine how players are positioned. Pressing high up the pitch vs. deep defence are contrasting strategic approaches.",
  "learnSch_physical_education_f1_kp2": "Decision-making: the best players constantly scan their environment, anticipate the next move, and choose the option that benefits the team rather than showing individual skill.",
  "learnSch_physical_education_f1_kp3": "Rules exist for fairness and safety. Understanding the offside rule (football), illegal screens (basketball), or rotation faults (volleyball) prevents mistakes and penalties.",
  "learnSch_physical_education_f1_kp4": "Leadership and sportsmanship: captains motivate and communicate; all players respect opponents, referees, and outcomes — core values of sport.",
  "learnSch_physical_education_f1_task": "Choose a team sport you play or watch. Design a practice drill to improve one specific skill (e.g. passing accuracy in football). State: the skill targeted, equipment needed, instructions for the drill, how to make it harder, and how to assess improvement.",
  "learnSch_physical_education_f1_tp0": "Teamwork and communication",
  "learnSch_physical_education_f1_tp1": "Tactics and game reading",
  "learnSch_physical_education_f1_tp2": "Rules and fair play",

  "learnSch_physical_education_f2_name": "Wellness & Healthy Lifestyle",
  "learnSch_physical_education_f2_desc": "Wellness is more than physical fitness — it encompasses mental health, sleep, nutrition, social connections, and stress management. A healthy lifestyle built on regular activity, balanced eating, adequate sleep, and positive relationships protects against chronic disease and supports well-being throughout life.",
  "learnSch_physical_education_f2_kp0": "The WHO recommends 150–300 minutes of moderate aerobic activity per week for adults (e.g. brisk walking, cycling) or 75 minutes of vigorous activity.",
  "learnSch_physical_education_f2_kp1": "Sleep: teenagers need 8–10 hours per night. Insufficient sleep impairs memory consolidation, mood, immune function, and reaction time.",
  "learnSch_physical_education_f2_kp2": "Stress management techniques: physical exercise, mindfulness, deep breathing, time management, and talking to a trusted person are all evidence-based approaches.",
  "learnSch_physical_education_f2_kp3": "Screen time: excessive use (especially social media at night) disrupts sleep and is linked to anxiety and low self-esteem in adolescents. Digital breaks and boundaries help.",
  "learnSch_physical_education_f2_kp4": "Substance awareness: alcohol and tobacco are legal but harmful — alcohol damages the liver and brain; smoking causes lung cancer and cardiovascular disease. Both are especially harmful for developing bodies.",
  "learnSch_physical_education_f2_task": "Create a personal weekly wellness plan. Include: 5 physical activity sessions (type, duration, intensity), a sleep schedule, 3 stress-management techniques, and 2 nutrition goals. Reflect on which area needs most improvement and why.",
  "learnSch_physical_education_f2_tp0": "Physical activity guidelines",
  "learnSch_physical_education_f2_tp1": "Sleep and stress management",
  "learnSch_physical_education_f2_tp2": "Digital health and substance awareness",

  // ── Religion & Ethics f2 ──────────────────────────────────────────────

  "learnSch_religion_ethics_f2_name": "Philosophical Ethics",
  "learnSch_religion_ethics_f2_desc": "Philosophical ethics asks: how should we act? What makes an action right or wrong? Three major ethical frameworks — consequentialism, deontology, and virtue ethics — offer different answers. Applying these frameworks to real-world dilemmas (euthanasia, climate justice, AI) develops clear, structured moral reasoning.",
  "learnSch_religion_ethics_f2_kp0": "Consequentialism (Utilitarianism — Mill, Bentham): an action is right if it produces the greatest happiness for the greatest number. Consequences determine morality.",
  "learnSch_religion_ethics_f2_kp1": "Deontology (Kant): some actions are intrinsically right or wrong, regardless of consequences. The Categorical Imperative: act only by rules you could will to be universal laws.",
  "learnSch_religion_ethics_f2_kp2": "Virtue ethics (Aristotle): focus on character rather than rules or outcomes. A virtuous person has cultivated habits of courage, honesty, justice, and temperance.",
  "learnSch_religion_ethics_f2_kp3": "Moral relativism: ethics vary between cultures and individuals — there is no universal standard. Moral absolutism: some actions are always right or wrong regardless of culture.",
  "learnSch_religion_ethics_f2_kp4": "Applied ethics examines specific controversies: medical ethics (euthanasia, abortion), environmental ethics (duties to non-human nature), and AI ethics (autonomous weapons, privacy).",
  "learnSch_religion_ethics_f2_task": "Apply each of the three major ethical frameworks (utilitarianism, deontology, virtue ethics) to this dilemma: 'Is it ethical to lie to protect someone's feelings?' For each, state the framework's core principle and its answer to the dilemma.",
  "learnSch_religion_ethics_f2_tp0": "Utilitarianism",
  "learnSch_religion_ethics_f2_tp1": "Kant and deontology",
  "learnSch_religion_ethics_f2_tp2": "Virtue ethics and applied ethics",

  // ── Social Studies f2 ─────────────────────────────────────────────────

  "learnSch_social_studies_f2_name": "Human Rights & Global Citizenship",
  "learnSch_social_studies_f2_desc": "Human rights are universal rights held by every person, regardless of nationality, gender, race, or religion. The Universal Declaration of Human Rights (1948) enshrines them in international law. Global citizenship means understanding your rights and responsibilities in an interconnected world and taking action for a just, sustainable future.",
  "learnSch_social_studies_f2_kp0": "The Universal Declaration of Human Rights (UDHR, 1948) has 30 articles covering civil, political, economic, social, and cultural rights — the foundation of international human rights law.",
  "learnSch_social_studies_f2_kp1": "First-generation rights: civil and political (free speech, right to a fair trial, right to vote). Second-generation: economic and social (right to education, healthcare, work).",
  "learnSch_social_studies_f2_kp2": "Human rights bodies: UN Human Rights Council, International Criminal Court (prosecutes war crimes and crimes against humanity), European Court of Human Rights.",
  "learnSch_social_studies_f2_kp3": "Child rights: the UN Convention on the Rights of the Child (1989) guarantees children's rights to education, protection, healthcare, and participation. Ratified by 196 countries.",
  "learnSch_social_studies_f2_kp4": "Global citizenship: taking responsibility for global issues (climate change, inequality, conflict) and acting locally and globally. NGOs (Amnesty International, Médecins Sans Frontières) embody this principle.",
  "learnSch_social_studies_f2_task": "Choose three articles from the Universal Declaration of Human Rights. For each: state the right, give a real-world example where this right is violated today, and suggest one action an individual or government could take.",
  "learnSch_social_studies_f2_tp0": "UDHR and international law",
  "learnSch_social_studies_f2_tp1": "Child rights",
  "learnSch_social_studies_f2_tp2": "Global citizenship and action",

  // ── Philosophy f2 ─────────────────────────────────────────────────────

  "learnSch_philosophy_f2_name": "Ethics & Moral Philosophy",
  "learnSch_philosophy_f2_desc": "Ethics is the branch of philosophy that asks how we should live and act. Moral philosophy examines the foundations of our values: what is good, what is just, and how should we treat others? These questions are not abstract — they underpin laws, medical decisions, AI development, and everyday choices.",
  "learnSch_philosophy_f2_kp0": "Moral realism: objective moral truths exist independently of what anyone thinks. Moral anti-realism: morality is constructed by people, societies, or is merely expression of emotion.",
  "learnSch_philosophy_f2_kp1": "The trolley problem (Judith Jarvis Thomson / Philippa Foot): would you divert a runaway trolley to kill one person and save five? Different frameworks give different answers.",
  "learnSch_philosophy_f2_kp2": "Justice (Rawls): design society from behind a 'veil of ignorance' — not knowing your own position, you choose fair rules everyone could agree to.",
  "learnSch_philosophy_f2_kp3": "Moral progress: societies change their ethical views over time — slavery was once legal and accepted; torture was once used in courts. This raises: is morality relative to time?",
  "learnSch_philosophy_f2_kp4": "Animal ethics: Peter Singer's utilitarian argument that animal suffering counts morally equally to human suffering. Does it? What follows for how we eat and research?",
  "learnSch_philosophy_f2_task": "Analyse the trolley problem using two different ethical frameworks. Which would each framework advise? Then design your own moral dilemma and analyse it. Discuss whether there is a 'right' answer or only better-reasoned ones.",
  "learnSch_philosophy_f2_tp0": "Moral realism vs. relativism",
  "learnSch_philosophy_f2_tp1": "Justice and Rawls",
  "learnSch_philosophy_f2_tp2": "Animal ethics and applied dilemmas",

  // ── Technology f2 ─────────────────────────────────────────────────────

  "learnSch_technology_f2_name": "Robotics & Automation",
  "learnSch_technology_f2_desc": "Robotics combines mechanical engineering, electronics, and programming to create machines that perform tasks autonomously or semi-autonomously. Automation — replacing human labour with machines — is transforming industry, medicine, and everyday life. Understanding robotics prepares you for a world where humans and machines increasingly work together.",
  "learnSch_technology_f2_kp0": "Robots have three main components: sensors (perceive the environment), actuators (move and act), and a controller (processes sensor data and decides actions — the 'brain').",
  "learnSch_technology_f2_kp1": "Degrees of freedom (DoF): the number of independent ways a robot can move. A robotic arm with 6 DoF can reach any position and orientation in 3D space.",
  "learnSch_technology_f2_kp2": "Industrial robots: welding, painting, assembly in car factories. Collaborative robots (cobots) work safely alongside humans. Surgical robots (Da Vinci) allow precision operations.",
  "learnSch_technology_f2_kp3": "Artificial Intelligence (AI) enhances robots with vision (recognising objects), natural language processing (voice commands), and machine learning (improving from experience).",
  "learnSch_technology_f2_kp4": "Automation and the economy: robots increase productivity but displace certain jobs. New jobs are created in robot maintenance, programming, and design. The net effect is debated.",
  "learnSch_technology_f2_task": "Design a simple robot to perform one specific task (e.g. sorting recyclables). Describe: sensors needed, actuators required, control logic (flowchart or pseudocode), and potential failure modes. Then discuss one ethical concern about automating this task.",
  "learnSch_technology_f2_tp0": "Robot components and DoF",
  "learnSch_technology_f2_tp1": "Industrial and medical robots",
  "learnSch_technology_f2_tp2": "AI and the future of work",

  // ════════════════════════════════════════════════════════════════════════
  // NEW SCHOOL SUBJECTS – COMPLETE (all 3 folders each)
  // ════════════════════════════════════════════════════════════════════════

  // ── Politics & Civics ─────────────────────────────────────────────────

  "learnSch_politics_civics_f0_name": "Democracy & Government Systems",
  "learnSch_politics_civics_f0_desc": "Government systems determine how a society is organised and how power is distributed. Democracy — rule by the people — takes many forms: direct, representative, presidential, and parliamentary. Comparing systems helps us understand why some countries are stable and free while others are authoritarian or unstable.",
  "learnSch_politics_civics_f0_kp0": "Democracy: citizens elect representatives who make laws on their behalf. Key principles: rule of law, separation of powers, freedom of expression, independent judiciary.",
  "learnSch_politics_civics_f0_kp1": "Presidential system (USA): executive (president) is directly elected and separate from the legislature. Parliamentary system (UK, Germany): the executive comes from and is accountable to parliament.",
  "learnSch_politics_civics_f0_kp2": "Separation of powers: legislative (makes laws), executive (implements laws), judicial (interprets laws). Checks and balances prevent any one branch from becoming too powerful.",
  "learnSch_politics_civics_f0_kp3": "Authoritarian regimes: power concentrated in one leader or party without genuine democratic accountability (e.g. North Korea, Belarus). Hybrid regimes: elections held but not free or fair.",
  "learnSch_politics_civics_f0_kp4": "The state: a territory with a permanent population, an effective government, and recognised sovereignty. Nations may contain multiple ethnic groups; nation-states align ethnicity with political borders.",
  "learnSch_politics_civics_f0_task": "Compare the political systems of the USA (presidential) and Germany (parliamentary). For each: describe how the executive is chosen, how laws are made, and what happens if the government loses public support. Which do you think has stronger democratic accountability? Justify.",
  "learnSch_politics_civics_f0_tp0": "Democracy and its forms",
  "learnSch_politics_civics_f0_tp1": "Separation of powers",
  "learnSch_politics_civics_f0_tp2": "Authoritarian systems",

  "learnSch_politics_civics_f1_name": "Human Rights & International Law",
  "learnSch_politics_civics_f1_desc": "International law governs relations between states and protects individuals' fundamental rights. The post-WWII order created the UN, the International Criminal Court, and treaties binding countries to uphold human rights. Understanding these institutions helps you assess how the world responds to conflict, injustice, and humanitarian crises.",
  "learnSch_politics_civics_f1_kp0": "The United Nations (founded 1945, 193 member states): maintains international peace and security, promotes development and human rights through its 15 specialised agencies.",
  "learnSch_politics_civics_f1_kp1": "International humanitarian law (Geneva Conventions): protects civilians, wounded soldiers, and prisoners of war during armed conflict. Violating them constitutes a war crime.",
  "learnSch_politics_civics_f1_kp2": "The International Criminal Court (ICC, The Hague): prosecutes individuals for genocide, crimes against humanity, and war crimes when national courts fail to act.",
  "learnSch_politics_civics_f1_kp3": "Sovereignty vs. intervention: states are sovereign (no outside interference in internal affairs), but the 'Responsibility to Protect' (R2P) doctrine allows intervention when a state commits mass atrocities.",
  "learnSch_politics_civics_f1_kp4": "Refugee law: the 1951 Refugee Convention defines a refugee as someone fleeing persecution based on race, religion, nationality, political opinion, or social group. States must not return them to danger (non-refoulement).",
  "learnSch_politics_civics_f1_task": "Research a current or recent international crisis (e.g. a conflict or humanitarian emergency). Identify: (a) which international laws apply, (b) what actions the UN or ICC has taken, (c) one argument for and one against military intervention.",
  "learnSch_politics_civics_f1_tp0": "United Nations system",
  "learnSch_politics_civics_f1_tp1": "International Criminal Court",
  "learnSch_politics_civics_f1_tp2": "Refugees and sovereignty",

  "learnSch_politics_civics_f2_name": "Political Participation & Elections",
  "learnSch_politics_civics_f2_desc": "Democratic participation goes beyond voting — it includes campaigning, petitioning, protesting, and running for office. Electoral systems determine how votes translate into seats and shape political outcomes. Understanding participation helps you exercise your rights and recognise the difference between healthy democracy and voter suppression.",
  "learnSch_politics_civics_f2_kp0": "Voting systems: First-Past-The-Post (UK, USA) — candidate with most votes wins, tends to produce two-party systems. Proportional Representation (Germany, Netherlands) — parties win seats in proportion to votes, encourages multi-party coalitions.",
  "learnSch_politics_civics_f2_kp1": "Political parties organise people with similar views to contest elections and form governments. Left-wing: greater equality, state intervention. Right-wing: individual freedom, free markets. Centre: moderate positions.",
  "learnSch_politics_civics_f2_kp2": "Voter turnout varies: high civic engagement strengthens democracy. Barriers include: complex registration, voter ID requirements, inaccessible polling stations, and disillusionment.",
  "learnSch_politics_civics_f2_kp3": "Non-electoral participation: petitions, demonstrations, civil disobedience (peaceful law-breaking to highlight injustice — used by Gandhi, Martin Luther King), social media activism.",
  "learnSch_politics_civics_f2_kp4": "Media and democracy: free press holds governments to account (4th estate). Filter bubbles and misinformation threaten informed voting — media literacy is a civic skill.",
  "learnSch_politics_civics_f2_task": "Compare FPTP and Proportional Representation using these criteria: fairness of representation, stability of government, voter choice, and likelihood of coalition. Then design a campaign for a school council election — write a manifesto, identify your voters, and plan three campaign activities.",
  "learnSch_politics_civics_f2_tp0": "Electoral systems",
  "learnSch_politics_civics_f2_tp1": "Political parties",
  "learnSch_politics_civics_f2_tp2": "Non-electoral participation",

  // ── Psychology (School Level) ─────────────────────────────────────────

  "learnSch_psychology_school_f0_name": "Introduction to Psychology",
  "learnSch_psychology_school_f0_desc": "Psychology is the scientific study of mind, brain, and behaviour. It seeks to understand why people think, feel, and act the way they do — from sleep and memory to love and aggression. Psychology's methods are scientific: controlled experiments, observation, and statistical analysis. It has transformed medicine, education, and everyday life.",
  "learnSch_psychology_school_f0_kp0": "Psychology's major perspectives: biological (brain, genes), cognitive (thought processes), behavioural (observable behaviour, conditioning), psychodynamic (unconscious drives), and humanistic (self-actualisation).",
  "learnSch_psychology_school_f0_kp1": "Scientific method in psychology: hypothesis → experiment → data collection → analysis → conclusion. Peer review ensures findings are checked before publication.",
  "learnSch_psychology_school_f0_kp2": "The brain's key areas: prefrontal cortex (decision-making, personality), amygdala (emotion, fear response), hippocampus (memory formation), cerebellum (coordination).",
  "learnSch_psychology_school_f0_kp3": "Nature vs. nurture debate: to what extent do genetics (nature) vs. environment and experience (nurture) shape personality, intelligence, and mental health? The current consensus: both interact.",
  "learnSch_psychology_school_f0_kp4": "Ethics in psychology: participants must give informed consent, can withdraw at any time, data is confidential, and studies must not cause lasting harm. The Milgram experiment (1960s) raised major ethical questions.",
  "learnSch_psychology_school_f0_task": "Design an ethical observational study to investigate whether students are more distracted when studying with music or in silence. State: the research question, method, variables, potential confounds, and how you would analyse the data.",
  "learnSch_psychology_school_f0_tp0": "Major perspectives",
  "learnSch_psychology_school_f0_tp1": "The brain and behaviour",
  "learnSch_psychology_school_f0_tp2": "Research methods and ethics",

  "learnSch_psychology_school_f1_name": "Cognition & Memory",
  "learnSch_psychology_school_f1_desc": "Cognition refers to all mental processes: perception, attention, memory, thinking, language, and problem-solving. Understanding memory — how it is formed, stored, and retrieved — is directly relevant to studying. Research shows that active recall and spaced repetition dramatically outperform passive re-reading for long-term retention.",
  "learnSch_psychology_school_f1_kp0": "The multi-store model (Atkinson & Shiffrin): sensory memory (fraction of a second) → short-term memory (7±2 items, ~20 sec) → long-term memory (unlimited capacity, potentially permanent).",
  "learnSch_psychology_school_f1_kp1": "Encoding: turning experience into memory traces. Elaborative encoding (linking new information to existing knowledge) is far more effective than rote repetition.",
  "learnSch_psychology_school_f1_kp2": "The spacing effect: studying the same material across multiple sessions over time (spaced repetition) leads to dramatically better long-term recall than massed 'cramming'.",
  "learnSch_psychology_school_f1_kp3": "Retrieval practice: actively recalling information (self-testing, flashcards) strengthens memory traces far more than re-reading. This is the 'testing effect'.",
  "learnSch_psychology_school_f1_kp4": "Memory is reconstructive, not reproductive: every time we recall a memory, we subtly alter it. Eyewitness testimony is therefore unreliable — shown repeatedly in courtroom research.",
  "learnSch_psychology_school_f1_task": "Test the spacing effect: study 20 new vocabulary words using massed practice (all at once today). Test yourself after 1 day. Then study 20 new words over 5 days (4 per day). Test after 7 days. Compare your scores and write up your findings.",
  "learnSch_psychology_school_f1_tp0": "Memory models",
  "learnSch_psychology_school_f1_tp1": "Encoding and retrieval",
  "learnSch_psychology_school_f1_tp2": "Study strategies from psychology",

  "learnSch_psychology_school_f2_name": "Social Psychology",
  "learnSch_psychology_school_f2_desc": "Social psychology studies how people think, feel, and behave in the presence of others — real or imagined. It reveals how profoundly our context shapes us: we conform to groups, obey authority, and develop biases — often unconsciously. Understanding social influence helps us make more independent, ethical decisions.",
  "learnSch_psychology_school_f2_kp0": "Conformity (Asch experiment, 1951): participants gave obviously wrong answers when they saw others give them — demonstrating normative (wanting to fit in) and informational (believing others are right) social influence.",
  "learnSch_psychology_school_f2_kp1": "Obedience (Milgram, 1963): participants administered apparently dangerous electric shocks because an authority figure told them to — 65% went to the maximum. Shows how authority overrides personal conscience.",
  "learnSch_psychology_school_f2_kp2": "Bystander effect: the more people present at an emergency, the less likely any one person is to help (diffusion of responsibility). Kitty Genovese case, 1964.",
  "learnSch_psychology_school_f2_kp3": "Attribution theory: we explain behaviour by attributing it to internal (personality, ability) or external (situation, luck) causes. Fundamental attribution error: overestimating internal causes for others' bad behaviour.",
  "learnSch_psychology_school_f2_kp4": "In-group and out-group bias: we favour people we identify with ('us') and can discriminate against others ('them'). Robbers Cave experiment showed how group competition breeds hostility.",
  "learnSch_psychology_school_f2_task": "You notice nobody in a crowded hall helps a person who has dropped their books and appears in pain. Using social psychology, explain: (a) why this might occur, (b) what specific factors increase or decrease the chance of helping, (c) what you personally could do to overcome the bystander effect.",
  "learnSch_psychology_school_f2_tp0": "Conformity and obedience",
  "learnSch_psychology_school_f2_tp1": "Bystander effect",
  "learnSch_psychology_school_f2_tp2": "Attribution and in-group bias",

  // ── Astronomy ─────────────────────────────────────────────────────────

  "learnSch_astronomy_f0_name": "The Solar System",
  "learnSch_astronomy_f0_desc": "Our solar system formed about 4.6 billion years ago from a cloud of gas and dust. It contains one star (the Sun), eight planets, dozens of moons, and countless smaller bodies — asteroids, comets, and dwarf planets. Understanding its structure and the forces that govern it connects physics, chemistry, and our place in the cosmos.",
  "learnSch_astronomy_f0_kp0": "The Sun contains 99.86% of the solar system's mass. It generates energy by nuclear fusion: hydrogen nuclei fuse to form helium, releasing enormous amounts of light and heat.",
  "learnSch_astronomy_f0_kp1": "Inner rocky planets: Mercury, Venus, Earth, Mars — small, dense, close to the Sun. Outer gas/ice giants: Jupiter, Saturn, Uranus, Neptune — much larger, farther from the Sun.",
  "learnSch_astronomy_f0_kp2": "Kepler's laws: planets orbit the Sun in ellipses (not circles); move faster when closer to the Sun; and the square of the orbital period is proportional to the cube of the orbital radius.",
  "learnSch_astronomy_f0_kp3": "The asteroid belt lies between Mars and Jupiter; the Kuiper Belt beyond Neptune contains Pluto and other dwarf planets. Comets originate from the Oort Cloud.",
  "learnSch_astronomy_f0_kp4": "Gravity holds everything in orbit. Escape velocity: the speed needed to break free from a body's gravity — Earth's is ~11.2 km/s; the Moon's is ~2.4 km/s.",
  "learnSch_astronomy_f0_task": "Create an annotated diagram of the solar system. For each planet: state its size relative to Earth, orbital period, one unique feature, and whether it could support life. Mark the asteroid belt and Kuiper Belt. Explain Kepler's 2nd law using your diagram.",
  "learnSch_astronomy_f0_tp0": "Sun and inner planets",
  "learnSch_astronomy_f0_tp1": "Outer planets and minor bodies",
  "learnSch_astronomy_f0_tp2": "Kepler's laws and gravity",

  "learnSch_astronomy_f1_name": "Stars & Stellar Evolution",
  "learnSch_astronomy_f1_desc": "Stars are not eternal — they are born, live, and die, often in spectacular explosions. A star's fate depends entirely on its mass. The Sun will eventually expand into a red giant and then collapse to a white dwarf, while more massive stars end as supernovae and neutron stars or black holes. All elements heavier than hydrogen were forged in stars.",
  "learnSch_astronomy_f1_kp0": "Stars form in nebulae (giant clouds of gas and dust) when gravity causes clumps to collapse and heat up until nuclear fusion ignites — birth of a protostar, then a main sequence star.",
  "learnSch_astronomy_f1_kp1": "Main sequence: stars spend most of their lives fusing hydrogen to helium in a stable state. The Sun has been on the main sequence for ~4.6 billion years and has ~5 billion left.",
  "learnSch_astronomy_f1_kp2": "The Hertzsprung-Russell (HR) diagram plots stars by luminosity vs. temperature. Main sequence runs diagonally; red giants (top right) and white dwarfs (bottom left) are off this line.",
  "learnSch_astronomy_f1_kp3": "Low-mass stars (like the Sun): main sequence → red giant → planetary nebula → white dwarf → (eventually) black dwarf.",
  "learnSch_astronomy_f1_kp4": "High-mass stars: main sequence → red supergiant → supernova explosion (creates elements heavier than iron, scatters them into space) → neutron star or black hole.",
  "learnSch_astronomy_f1_task": "Draw two stellar evolution pathways on an HR diagram: one for a star like the Sun, one for a star 20 times more massive. For each stage: state the name, timescale, and the main nuclear process occurring. Explain what a supernova is and why it matters for the origin of elements on Earth.",
  "learnSch_astronomy_f1_tp0": "Star formation and main sequence",
  "learnSch_astronomy_f1_tp1": "HR diagram",
  "learnSch_astronomy_f1_tp2": "Supernovae and black holes",

  "learnSch_astronomy_f2_name": "Galaxies & Cosmology Basics",
  "learnSch_astronomy_f2_desc": "Beyond our solar system lie billions of stars grouped into galaxies, and beyond galaxies lies the observable universe — about 93 billion light-years across and 13.8 billion years old. Cosmology — the science of the universe's origin and evolution — has revealed an astonishing picture: the Big Bang, expanding space, dark matter, and dark energy.",
  "learnSch_astronomy_f2_kp0": "The Milky Way is a barred spiral galaxy containing ~250 billion stars. Our Sun is located ~27,000 light-years from the galactic centre. It takes the Sun ~225 million years to orbit the galaxy.",
  "learnSch_astronomy_f2_kp1": "Galaxy types: spiral (like the Milky Way and Andromeda), elliptical (older stars, little gas), irregular (no defined shape, often result of galactic collisions).",
  "learnSch_astronomy_f2_kp2": "The Big Bang theory: ~13.8 billion years ago, the universe began as an extremely hot, dense point and has been expanding ever since. Evidence: cosmic microwave background radiation, Hubble's law (galaxies recede faster the farther they are).",
  "learnSch_astronomy_f2_kp3": "Dark matter: invisible matter that does not emit light but whose gravitational effects hold galaxies together. Makes up ~27% of the universe's mass-energy. Its nature is unknown.",
  "learnSch_astronomy_f2_kp4": "Dark energy: a mysterious force driving the accelerating expansion of the universe. Makes up ~68% of the universe. Ordinary matter (stars, planets, gas) is only ~5%.",
  "learnSch_astronomy_f2_task": "Create an 'address' for Earth: planet, star system, galaxy, galaxy group, supercluster, observable universe. Provide a distance/size for each level. Then explain two pieces of evidence for the Big Bang theory, including what the cosmic microwave background radiation is.",
  "learnSch_astronomy_f2_tp0": "Galaxies and the Milky Way",
  "learnSch_astronomy_f2_tp1": "Big Bang and expansion",
  "learnSch_astronomy_f2_tp2": "Dark matter and dark energy",

  // ── Latin Language ────────────────────────────────────────────────────

  "learnSch_latin_language_f0_name": "Latin Grammar Fundamentals",
  "learnSch_latin_language_f0_desc": "Latin is an inflected language — word endings (not word order) show grammatical function. Mastering noun declensions and verb conjugations unlocks the meaning of any Latin text, from Caesar's war reports to Virgil's epic poetry. Latin grammar also improves understanding of English, French, Spanish, Italian, and Portuguese.",
  "learnSch_latin_language_f0_kp0": "Latin has five noun declensions. Each declension has six cases: nominative (subject), accusative (object), genitive (possession), dative (indirect object), ablative (various), vocative (address).",
  "learnSch_latin_language_f0_kp1": "Example 1st declension: puella (girl) — puella (nom.), puellam (acc.), puellae (gen.), puellae (dat.), puella (abl.), puella (voc.). Plural: puellae, puellas, puellarum, puellis, puellis, puellae.",
  "learnSch_latin_language_f0_kp2": "Verbs are conjugated for person (1st/2nd/3rd), number (singular/plural), tense (present, imperfect, perfect, future), voice (active/passive), and mood (indicative, subjunctive, imperative).",
  "learnSch_latin_language_f0_kp3": "Present tense of amare (to love): amo, amas, amat, amamus, amatis, amant — I love, you love, he/she/it loves, we love, you (pl.) love, they love.",
  "learnSch_latin_language_f0_kp4": "Word order in Latin is flexible because endings convey function: 'Puella aquam portat' and 'Aquam puella portat' both mean 'The girl carries water.' Emphasis shifts but meaning stays.",
  "learnSch_latin_language_f0_task": "Decline the noun 'dominus' (master, 2nd declension masculine) in all six cases, singular and plural. Then conjugate 'videre' (to see) in the present tense, all persons. Translate: 'Dominus puellas amat' and 'Puellae dominum vident'.",
  "learnSch_latin_language_f0_tp0": "Noun declensions and cases",
  "learnSch_latin_language_f0_tp1": "Verb conjugations",
  "learnSch_latin_language_f0_tp2": "Latin sentence structure",

  "learnSch_latin_language_f1_name": "Reading Latin Texts",
  "learnSch_latin_language_f1_desc": "Reading authentic Latin texts — Caesar, Cicero, Virgil, Ovid — connects you to 2,000 years of Western thought, law, literature, and science. The skill of translation builds analytical precision, patience, and the ability to work with complex sentences. Even simple texts reveal Roman values, history, and rhetoric.",
  "learnSch_latin_language_f1_kp0": "Translation strategy: identify the verb first (it tells you the action and tense), then the subject (nominative), then the object (accusative), then other elements.",
  "learnSch_latin_language_f1_kp1": "Caesar's 'De Bello Gallico' is written in plain, military Latin — ideal for beginners. Cicero's speeches use complex rhetoric. Virgil's 'Aeneid' is poetry with metre and figurative language.",
  "learnSch_latin_language_f1_kp2": "Subordinate clauses: accusative + infinitive (indirect statement), cum clauses (when/since), relative clauses (qui, quae, quod — who, which), result clauses (ut + subjunctive).",
  "learnSch_latin_language_f1_kp3": "Perfect tense: past actions completed. Regular perfect endings: -i, -isti, -it, -imus, -istis, -erunt. Example: amavi = I loved / I have loved.",
  "learnSch_latin_language_f1_kp4": "Reading strategies: context clues help when grammar is unclear. Use knowledge of root words — many English words are Latin derivatives (e.g. 'port' from portare = to carry).",
  "learnSch_latin_language_f1_task": "Translate this passage from Caesar: 'Milites Romani castrum magnum aedificaverunt. Galli per silvas fugerunt et in montibus se celaverunt.' Analyse: identify subject, verb, object, and any ablative phrases. What tense are the verbs? What does this tell us about what already happened?",
  "learnSch_latin_language_f1_tp0": "Translation method",
  "learnSch_latin_language_f1_tp1": "Caesar and Cicero texts",
  "learnSch_latin_language_f1_tp2": "Subordinate clauses",

  "learnSch_latin_language_f2_name": "Roman Culture through Language",
  "learnSch_latin_language_f2_desc": "Latin was not just a language — it was the vehicle of an entire civilisation that shaped law, architecture, religion, and political thought across Europe and the world. Roman concepts embedded in Latin — res publica, imperium, senatus, ius — directly gave us 'republic', 'empire', 'senate', and 'justice'. Understanding this legacy is inseparable from understanding Western history.",
  "learnSch_latin_language_f2_kp0": "Latin's legacy: ~60% of English vocabulary is derived from Latin or Latin-influenced French. Scientific names, legal terms, and medical vocabulary are predominantly Latin.",
  "learnSch_latin_language_f2_kp1": "Roman legal concepts still in use: habeas corpus (you must produce the body — right not to be imprisoned without charge), sub judice (under a judge), in absentia, pro bono, ex parte.",
  "learnSch_latin_language_f2_kp2": "Roman religious and cultural contributions: the calendar (months named after Roman gods and emperors: January/Janus, March/Mars, July/Julius Caesar), architectural orders (Doric, Ionic, Corinthian).",
  "learnSch_latin_language_f2_kp3": "Latin mottos still used: carpe diem (seize the day), cogito ergo sum (I think, therefore I am), veni vidi vici (I came, I saw, I conquered — Julius Caesar), e pluribus unum (out of many, one — USA motto).",
  "learnSch_latin_language_f2_kp4": "Roman literature: Virgil's 'Aeneid' (epic founding myth of Rome), Ovid's 'Metamorphoses' (myths of transformation), Cicero's speeches, Caesar's military commentaries — all still read and studied today.",
  "learnSch_latin_language_f2_task": "Find 10 English words derived from Latin roots in one paragraph of any textbook. For each: write the Latin root, its meaning, and the English word. Then explain one Roman legal concept and show how it applies in a modern legal system.",
  "learnSch_latin_language_f2_tp0": "Latin roots in English and science",
  "learnSch_latin_language_f2_tp1": "Roman law and politics",
  "learnSch_latin_language_f2_tp2": "Latin literature and culture",

  // ── Media Studies ─────────────────────────────────────────────────────

  "learnSch_media_studies_f0_name": "Media Literacy",
  "learnSch_media_studies_f0_desc": "Media literacy is the ability to access, analyse, evaluate, and create media. In a world saturated with information — news, social media, advertising, entertainment — the ability to critically assess sources, identify bias, and recognise manipulation is a fundamental democratic skill. Media literate citizens are harder to deceive.",
  "learnSch_media_studies_f0_kp0": "All media messages are constructed: they are made by someone, for a purpose, for an audience, using specific techniques, with potential effects. CAGE framework: Construction, Audience, Genre, Effect.",
  "learnSch_media_studies_f0_kp1": "Bias in news: selection bias (what stories are covered), framing bias (how they are presented), and source bias (whose voices are heard). All media outlets have some bias — the question is how much and in which direction.",
  "learnSch_media_studies_f0_kp2": "Misinformation: false information spread without intent to deceive. Disinformation: deliberately false information created to mislead. Fact-checking websites (Snopes, Full Fact, Politifact) help verify claims.",
  "learnSch_media_studies_f0_kp3": "Advertising techniques: emotional appeal, celebrity endorsement, bandwagon ('everyone uses it'), scarcity ('limited offer'), repetition. Advertising works subconsciously — even if we know the tricks.",
  "learnSch_media_studies_f0_kp4": "Ownership matters: a small number of companies own most global media (News Corp, Disney, Google, Meta). Concentrated ownership can limit diversity of viewpoints.",
  "learnSch_media_studies_f0_task": "Choose one news story covered by three different outlets (e.g. a BBC article, a tabloid, and a social media post). Compare: headline, tone, evidence used, whose quotes are included, and what is left out. Rate each for reliability. Conclude which is most trustworthy and why.",
  "learnSch_media_studies_f0_tp0": "Media construction and bias",
  "learnSch_media_studies_f0_tp1": "Misinformation and fact-checking",
  "learnSch_media_studies_f0_tp2": "Advertising techniques",

  "learnSch_media_studies_f1_name": "Film & Visual Media",
  "learnSch_media_studies_f1_desc": "Film is one of the most powerful storytelling media ever invented. It combines image, sound, movement, and editing to create meaning. Learning to 'read' film like a text — analysing camera angles, lighting, sound design, and narrative structure — opens up a richer experience of cinema and gives you tools to create your own visual stories.",
  "learnSch_media_studies_f1_kp0": "Camera shots: extreme close-up (emotion, detail), close-up (character reaction), medium shot (character + context), long shot (setting), extreme long shot (isolation, landscape). Each creates different emotional effects.",
  "learnSch_media_studies_f1_kp1": "Camera angles: low angle (makes subject look powerful), high angle (makes subject look small/vulnerable), eye level (neutral), Dutch tilt (unease/tension). Point of view shots immerse the viewer in a character's perspective.",
  "learnSch_media_studies_f1_kp2": "Editing: cut (instant transition), fade (gradual to black — suggests time passing), dissolve (overlap — suggests connection). Montage editing creates meaning through sequence (Eisenstein).",
  "learnSch_media_studies_f1_kp3": "Sound: diegetic sound (exists in the film world — dialogue, footsteps), non-diegetic (soundtrack heard only by audience). Music creates mood; silence creates tension.",
  "learnSch_media_studies_f1_kp4": "Mise-en-scène: everything placed in the frame — set design, costumes, lighting, actor positioning. Each element communicates meaning deliberately.",
  "learnSch_media_studies_f1_task": "Choose a 2-minute scene from a film. Analyse: (a) three different shot types used and their effect, (b) lighting (high-key = bright/cheerful or low-key = dark/mysterious?), (c) sound (describe diegetic and non-diegetic), (d) how editing creates pace. Conclude what mood is created and how.",
  "learnSch_media_studies_f1_tp0": "Camera shots and angles",
  "learnSch_media_studies_f1_tp1": "Editing techniques",
  "learnSch_media_studies_f1_tp2": "Sound and mise-en-scène",

  "learnSch_media_studies_f2_name": "Digital Media & Social Networks",
  "learnSch_media_studies_f2_desc": "Social media platforms have transformed how people communicate, consume news, and form identities. They have also introduced new risks: algorithmic manipulation, cyberbullying, privacy erosion, and political polarisation. Understanding how platforms work and how to use them critically and safely is essential digital citizenship.",
  "learnSch_media_studies_f2_kp0": "Algorithms personalise content based on your behaviour — what you click, like, and share. This creates filter bubbles where you see only confirming viewpoints, amplifying polarisation.",
  "learnSch_media_studies_f2_kp1": "Business model: most social platforms are free because users' data and attention are the product sold to advertisers. 'If you're not paying, you are the product.'",
  "learnSch_media_studies_f2_kp2": "Digital footprint: everything you post, like, or search leaves a permanent trace. Future employers, universities, and law enforcement can access your public and sometimes private content.",
  "learnSch_media_studies_f2_kp3": "Cyberbullying: online harassment that can be anonymous, reach victims anywhere, and leave a permanent record. Effects on mental health are severe; it is a legal offence in most countries.",
  "learnSch_media_studies_f2_kp4": "Deepfakes and synthetic media: AI can create convincing fake videos of real people. This makes visual evidence increasingly untrustworthy — 'seeing' is no longer 'believing'.",
  "learnSch_media_studies_f2_task": "Audit your own social media presence: what image of you do your public posts create? What does your algorithm show you? Do you follow accounts with opposing viewpoints? Then design a guide for a Year 7 student on safe and critical social media use — include 5 specific, practical tips.",
  "learnSch_media_studies_f2_tp0": "Algorithms and filter bubbles",
  "learnSch_media_studies_f2_tp1": "Digital footprint and privacy",
  "learnSch_media_studies_f2_tp2": "Cyberbullying and deepfakes",

  // ── Chinese Language ──────────────────────────────────────────────────

  "learnSch_chinese_language_f0_name": "Mandarin Foundations: Pinyin & Tones",
  "learnSch_chinese_language_f0_desc": "Mandarin Chinese has over 1 billion speakers worldwide and is the most spoken language by native speakers. Unlike alphabetic languages, Mandarin uses tones — changes in pitch that change meaning — and a logographic writing system. Mastering the Pinyin romanisation system and the four tones is the essential first step.",
  "learnSch_chinese_language_f0_kp0": "Pinyin: the official romanisation system for Mandarin. It uses Latin letters with tone marks to represent pronunciation. Essential for learning characters and using digital input methods.",
  "learnSch_chinese_language_f0_kp1": "The four tones: 1st (high level, ā) — 'mā' means mother. 2nd (rising, á) — 'má' means hemp. 3rd (dipping, ǎ) — 'mǎ' means horse. 4th (falling, à) — 'mà' means to scold. Plus neutral tone (no mark).",
  "learnSch_chinese_language_f0_kp2": "Initials (consonants): b, p, m, f, d, t, n, l, g, k, h, j, q, x, zh, ch, sh, r, z, c, s. Finals (vowels and endings): a, o, e, i, u, ü, ai, ei, ao, ou, an, en, ang, eng, ong, etc.",
  "learnSch_chinese_language_f0_kp3": "Essential greetings: 你好 (nǐ hǎo) — hello; 谢谢 (xièxiè) — thank you; 不客气 (bù kèqì) — you're welcome; 对不起 (duìbuqǐ) — sorry; 再见 (zàijiàn) — goodbye.",
  "learnSch_chinese_language_f0_kp4": "Mandarin grammar is simpler than European languages in some ways: no verb conjugation, no grammatical gender, no plural endings. Word order (Subject-Verb-Object) carries meaning.",
  "learnSch_chinese_language_f0_task": "Listen to all four tones of 'ma' and repeat until you can produce each distinctly. Write 'I am a student' in Mandarin using Pinyin: 'Wǒ shì xuéshēng.' Then write: 'I want to eat rice' — 'Wǒ xiǎng chī mǐfàn.' Explain the difference in meaning caused by tone change in 'mā/mǎ'.",
  "learnSch_chinese_language_f0_tp0": "Four tones",
  "learnSch_chinese_language_f0_tp1": "Pinyin system",
  "learnSch_chinese_language_f0_tp2": "Basic greetings and phrases",

  "learnSch_chinese_language_f1_name": "Characters & the Writing System",
  "learnSch_chinese_language_f1_desc": "Chinese characters (汉字, Hànzì) are one of the world's oldest writing systems, with over 50,000 characters — though literacy requires knowing about 2,000–3,000 common ones. Characters are not random drawings — they are built from meaningful components called radicals, which provide clues to meaning and sometimes pronunciation.",
  "learnSch_chinese_language_f1_kp0": "Characters are written on a square grid and composed of strokes in a specific order. Stroke order rules ensure consistency and aid memory: generally top to bottom, left to right, horizontal before vertical.",
  "learnSch_chinese_language_f1_kp1": "Radicals: all characters contain a semantic radical that hints at meaning. 水 (water radical 氵) appears in 海 (sea), 河 (river), 泳 (swim). Knowing ~200 radicals unlocks patterns in thousands of characters.",
  "learnSch_chinese_language_f1_kp2": "Simplified vs. Traditional: Simplified characters (used in mainland China, Singapore) have fewer strokes. Traditional characters (Taiwan, Hong Kong, overseas communities) preserve historical forms. Example: love — 爱 (simplified) vs. 愛 (traditional).",
  "learnSch_chinese_language_f1_kp3": "HSK (Hanyu Shuiping Kaoshi): the standard Chinese proficiency test. HSK 1 = 150 words, HSK 2 = 300, up to HSK 6 = 5,000 words. Essential benchmark for Chinese learners.",
  "learnSch_chinese_language_f1_kp4": "Common characters to learn first: 一二三四五六七八九十 (1–10), 人 (person), 大 (big), 小 (small), 中 (middle/China), 日 (sun/day), 月 (moon/month), 山 (mountain), 水 (water), 火 (fire).",
  "learnSch_chinese_language_f1_task": "Learn and write (with correct stroke order) the numbers 1–10 in Chinese characters. Then learn five more characters using their radicals as memory aids — explain the connection for each. Finally, write your name in Pinyin and choose appropriate Chinese characters for it.",
  "learnSch_chinese_language_f1_tp0": "Stroke order and structure",
  "learnSch_chinese_language_f1_tp1": "Radicals and patterns",
  "learnSch_chinese_language_f1_tp2": "Simplified vs. Traditional characters",

  "learnSch_chinese_language_f2_name": "Conversational Chinese",
  "learnSch_chinese_language_f2_desc": "Learning conversational Mandarin opens doors to 1.4 billion potential conversations and one of the world's most vibrant cultures. Core topics — introductions, time, shopping, food, directions — provide the practical vocabulary for everyday communication. Chinese grammar's regularity makes dialogue surprisingly accessible once tones and basic vocabulary are mastered.",
  "learnSch_chinese_language_f2_kp0": "Sentence structure: Subject + Time + Place + Verb + Object. Example: 我 (I) 明天 (tomorrow) 在图书馆 (in the library) 学习 (study) 中文 (Chinese) = 我明天在图书馆学习中文.",
  "learnSch_chinese_language_f2_kp1": "Asking questions: add 吗 (ma) to a statement for yes/no questions. 你是学生 (you are a student) → 你是学生吗? (Are you a student?). Or use question words: 什么 (shénme, what), 哪里 (nǎlǐ, where), 什么时候 (shénme shíhòu, when).",
  "learnSch_chinese_language_f2_kp2": "Numbers and prices: 一百 (100), 两百五十 (250). In shops: 这个多少钱? (zhège duōshǎo qián?) — How much is this? 太贵了 (tài guì le) — Too expensive! 便宜一点 (piányí yīdiǎn) — A little cheaper please.",
  "learnSch_chinese_language_f2_kp3": "Food and ordering: 我要一碗米饭 (Wǒ yào yī wǎn mǐfàn) — I want a bowl of rice. 我不吃肉 (Wǒ bù chī ròu) — I don't eat meat. 好吃! (Hǎochī!) — Delicious!",
  "learnSch_chinese_language_f2_kp4": "Cultural context: exchanging business cards with two hands; addressing elders formally; the importance of 面子 (miànzi, 'face' — reputation, dignity); gift-giving etiquette. Language and culture are inseparable.",
  "learnSch_chinese_language_f2_task": "Role-play (write or record) a conversation at a Chinese restaurant. Include: greeting the waiter, asking what is good, ordering two dishes and a drink (using correct measure words), asking the price, and saying goodbye. Aim for at least 10 exchanges. Annotate with Pinyin and English translation.",
  "learnSch_chinese_language_f2_tp0": "Sentence structure and questions",
  "learnSch_chinese_language_f2_tp1": "Shopping and numbers",
  "learnSch_chinese_language_f2_tp2": "Food, culture, and daily life",

  // ── Environmental Studies (School) ────────────────────────────────────

  "learnSch_environmental_studies_f0_name": "Climate Change & the Carbon Cycle",
  "learnSch_environmental_studies_f0_desc": "Climate change is the defining challenge of our era. Human emissions of greenhouse gases are warming Earth at an unprecedented rate, disrupting weather patterns, melting ice caps, and threatening ecosystems and human communities. Understanding the science — the carbon cycle, tipping points, and feedback loops — is essential for any informed citizen.",
  "learnSch_environmental_studies_f0_kp0": "The carbon cycle: CO₂ moves between atmosphere, oceans, land (plants via photosynthesis), and living organisms (via respiration). Burning fossil fuels releases carbon stored for millions of years, disrupting the cycle.",
  "learnSch_environmental_studies_f0_kp1": "Greenhouse effect: solar radiation warms Earth; Earth emits infrared radiation; greenhouse gases (CO₂, CH₄, N₂O, H₂O vapour) absorb it and re-radiate heat, warming the surface. Without it, Earth would be −18°C; with it (natural), 15°C; enhanced = dangerous warming.",
  "learnSch_environmental_studies_f0_kp2": "Current status (2024): atmospheric CO₂ exceeds 420 ppm (pre-industrial: 280 ppm). Global average temperature has risen ~1.2°C above pre-industrial levels. The Paris Agreement aims to limit warming to 1.5°C.",
  "learnSch_environmental_studies_f0_kp3": "Climate tipping points: thresholds beyond which changes become self-reinforcing. Melting permafrost releases CH₄; melting Arctic ice exposes dark ocean, absorbing more heat; Amazon deforestation risks turning the rainforest into savanna.",
  "learnSch_environmental_studies_f0_kp4": "Climate justice: developing nations contribute least to emissions but suffer most from climate impacts (sea-level rise, extreme heat, crop failure). The ethical and political dimensions of climate action are inseparable from the science.",
  "learnSch_environmental_studies_f0_task": "Draw and annotate the carbon cycle, showing natural flows and the human disruption. Calculate: if a country emits 500 Mt CO₂ per year and plants trees sequestering 50 Mt/year while switching to renewables saves 100 Mt/year, how many years to reach net zero (assuming no new measures)? Evaluate three additional actions the country could take.",
  "learnSch_environmental_studies_f0_tp0": "Carbon cycle and greenhouse effect",
  "learnSch_environmental_studies_f0_tp1": "Current data and Paris Agreement",
  "learnSch_environmental_studies_f0_tp2": "Tipping points and climate justice",

  "learnSch_environmental_studies_f1_name": "Ecosystems & Biodiversity",
  "learnSch_environmental_studies_f1_desc": "Biodiversity — the variety of life on Earth — is the foundation of healthy ecosystems that provide us with food, clean water, medicine, and a stable climate. We are currently experiencing the sixth mass extinction, driven by habitat destruction, pollution, invasive species, and climate change. Understanding ecosystems reveals why every lost species matters.",
  "learnSch_environmental_studies_f1_kp0": "Ecosystem services: the benefits nature provides free of charge — pollination (essential for 75% of food crops), water purification, flood control, carbon storage, soil formation, and coastal protection.",
  "learnSch_environmental_studies_f1_kp1": "The sixth mass extinction: species are going extinct 100–1,000 times faster than the natural background rate. ~1 million species currently threatened. Primary causes: land-use change (habitat loss), overexploitation, pollution, invasive species, climate change.",
  "learnSch_environmental_studies_f1_kp2": "Keystone species: species that play a disproportionately large role in their ecosystem. Removing them causes ecosystem collapse — e.g. wolves in Yellowstone controlled deer populations, which allowed vegetation to recover, affecting rivers.",
  "learnSch_environmental_studies_f1_kp3": "Biomes: large ecological communities defined by climate and vegetation — tropical rainforest (maximum biodiversity), temperate forest, grassland/savanna, desert (extreme conditions), tundra (permafrost), ocean (largest biome).",
  "learnSch_environmental_studies_f1_kp4": "Conservation strategies: protected areas (national parks, marine reserves), rewilding (restoring natural species and processes), ex-situ conservation (zoos, seed banks), CITES treaty (controls trade in endangered species).",
  "learnSch_environmental_studies_f1_task": "Research one endangered ecosystem (e.g. coral reefs, Amazon rainforest, peat bogs). For your chosen ecosystem: (a) describe its biodiversity, (b) explain three threats, (c) quantify the economic value of its ecosystem services, (d) evaluate three conservation strategies and their effectiveness.",
  "learnSch_environmental_studies_f1_tp0": "Ecosystem services",
  "learnSch_environmental_studies_f1_tp1": "Sixth mass extinction",
  "learnSch_environmental_studies_f1_tp2": "Conservation strategies",

  "learnSch_environmental_studies_f2_name": "Sustainability & Solutions",
  "learnSch_environmental_studies_f2_desc": "Sustainability means meeting the needs of the present without compromising the ability of future generations to meet theirs (Brundtland definition, 1987). Transitioning to a sustainable world requires changes in energy, food, transport, and consumption — and involves everyone from governments and corporations to individuals.",
  "learnSch_environmental_studies_f2_kp0": "Sustainable Development Goals (SDGs): 17 goals adopted by all UN member states in 2015, targeting poverty, health, education, clean energy, climate action, and biodiversity by 2030.",
  "learnSch_environmental_studies_f2_kp1": "Renewable energy: solar, wind, hydro, geothermal, and tidal power produce electricity with minimal greenhouse gas emissions. Solar and wind costs have fallen 90%+ since 2010 — they are now the cheapest energy sources ever built.",
  "learnSch_environmental_studies_f2_kp2": "Circular economy: instead of take–make–dispose, materials are reused, repaired, and recycled in closed loops. Reduces waste, saves resources, and creates jobs.",
  "learnSch_environmental_studies_f2_kp3": "Food systems: agriculture accounts for ~25% of global greenhouse gas emissions. Reducing meat consumption (especially beef), cutting food waste, and shifting to sustainable farming (organic, agroforestry) are major levers.",
  "learnSch_environmental_studies_f2_kp4": "Individual action matters: carbon footprints vary enormously. Flying, eating meat, and driving petrol cars are the highest-impact individual choices. But systemic change — government policy, corporate practice, infrastructure — has far greater total impact.",
  "learnSch_environmental_studies_f2_task": "Calculate your monthly carbon footprint using an online calculator. Identify your three highest-impact activities. Research and propose one personal change and one systemic change (government or corporate policy) that would reduce your footprint. Present: current footprint, target footprint, and timeline.",
  "learnSch_environmental_studies_f2_tp0": "SDGs and renewable energy",
  "learnSch_environmental_studies_f2_tp1": "Circular economy",
  "learnSch_environmental_studies_f2_tp2": "Food systems and individual vs. systemic action"

};

const before = Object.keys(en).length;
Object.assign(en, keys);
const after = Object.keys(en).length;
fs.writeFileSync(enPath, JSON.stringify(en, null, 2), 'utf8');
console.log('Batch C done. Added', after - before, 'new keys. Total:', after);
